services:
  gateway:
    build: .
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      TELEGRAM_ID: ${TELEGRAM_ID}
      TELEGRAM_HASH: ${TELEGRAM_HASH}
      TELEGRAM_ADMIN_USER_ID: ${TELEGRAM_ADMIN_USER_ID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
