services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ messaging port
      - '15672:15672' # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - '9000:9000' # MinIO API port
      - '9001:9001' # MinIO Console UI port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --requirepass $REDIS_PASSWORD
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '$REDIS_PASSWORD', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    ports:
      - '5540:5540' # Map host port 8001 to container port 8001
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: '6379'
      RI_REDIS_ALIAS: local
      RI_REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  rabbitmq_data:
  minio_data:
  redis_data:
  redisinsight_data:
